name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless


  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Check vulnerabilities
        run: npm audit --audit-level=high


  build-and-deploy:
    needs: [test, audit]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Create environment file
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  SERVICE_ID: '${{ secrets.SERVICE_ID }}'," >> src/environments/environment.prod.ts
          echo "  API_KEY: '${{ secrets.API_KEY }}'," >> src/environments/environment.prod.ts
          echo "  TEMPLATE_ID: '${{ secrets.TEMPLATE_ID }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Build project
        run: npm run build -- --configuration=production --base-href=/

      - name: Create CNAME file
        run: echo "weuller.com.br" > docs/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
